### ISSUE TITLE
TypeError when handling message after new user connects

### ISSUE THREAD

**Issue by campbellr** [loafoe/mattermost-client#10]
When using the `hubot-matteruser` adaptor for hubot I've noticed that whenever a new user connects, the next message to hubot seem to fail with a TypeError:

```
Fri May 27 2016 13:03:55 GMT-0600 (MDT) [APP] OUT [Fri May 27 2016 19:03:55 GMT+0000 (UTC)] DEBUG GET /users/profiles
Fri May 27 2016 13:03:55 GMT-0600 (MDT) [APP] OUT [Fri May 27 2016 19:03:55 GMT+0000 (UTC)] DEBUG Found 2 profiles.
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT [Fri May 27 2016 19:04:06 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'username' of undefined
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Client.<anonymous> (/home/vcap/app/node_modules/hubot-matteruser/src/matteruser.coffee:1:1, <js>:3:61)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Matteruser.message (/home/vcap/app/node_modules/hubot-matteruser/src/matteruser.coffee:126:29, <js>:199:64)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Client.emit (events.js:95:17)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Client.onMessage (/home/vcap/app/node_modules/mattermost-client/src/client.coffee:206:17, <js>:274:23)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at WebSocket.<anonymous> (/home/vcap/app/node_modules/mattermost-client/src/client.coffee:154:13, <js>:213:22)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at WebSocket.emit (events.js:98:17)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Receiver.ontext (/home/vcap/app/node_modules/ws/lib/WebSocket.js:841:10)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at /home/vcap/app/node_modules/ws/lib/Receiver.js:536:18
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Receiver.applyExtensions (/home/vcap/app/node_modules/ws/lib/Receiver.js:371:5)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at /home/vcap/app/node_modules/ws/lib/Receiver.js:508:14
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Receiver.flush (/home/vcap/app/node_modules/ws/lib/Receiver.js:347:3)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Receiver.expectHandler (/home/vcap/app/node_modules/ws/lib/Receiver.js:499:31)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Receiver.opcodes.1.finish (/home/vcap/app/node_modules/ws/lib/Receiver.js:541:12)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at Receiver.add (/home/vcap/app/node_modules/ws/lib/Receiver.js:103:24)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at CleartextStream.realHandler (/home/vcap/app/node_modules/ws/lib/WebSocket.js:825:20)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at CleartextStream.emit (events.js:95:17)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at CleartextStream.<anonymous> (_stream_readable.js:765:14)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at CleartextStream.emit (events.js:92:17)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at emitReadable_ (_stream_readable.js:427:10)
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at _stream_readable.js:420:7
Fri May 27 2016 13:04:06 GMT-0600 (MDT) [APP] OUT at process._tickCallback (node.js:458:13)

```

I've poked around the code a bit and I think it might be because of an incorrect url in [client.coffee#L215](https://github.com/loafoe/mattermost-client/blob/master/src/client.coffee#L215).

The team is missing from the URL which seems to result in a 404.

**Comment by campbellr** [comment]
Awesome, thanks for the quick fix.
