### ISSUE TITLE
Error when getting the channels

### ISSUE THREAD

**Issue by msanand** [loafoe/mattermost-client#11]
Hi,

Firstly, thanks for the awesome matteruser adapter! I'm trying to switch from hubot-mattermost to your adapter. Unfortunately when I load hubot with the adapter I see the following error:  

> [Tue May 31 2016 22:32:01 GMT+0530 (IST)] INFO Logging in...
[Tue May 31 2016 22:32:02 GMT+0530 (IST)] INFO Websocket URL: wss://mattermost.mo.sap.corp:443/api/v3/users/websocket
[Tue May 31 2016 22:32:02 GMT+0530 (IST)] INFO Logged in as user "jarvis" but not connected yet.
[Tue May 31 2016 22:32:02 GMT+0530 (IST)] INFO Connecting...
[Tue May 31 2016 22:32:02 GMT+0530 (IST)] ERROR TypeError: Cannot convert undefined or null to object
  at Client._onChannels (/home/i055636/git/alfred/node_modules/mattermost-client/src/client.coffee:95:13, <js>:141:45)
  at /home/i055636/git/alfred/node_modules/mattermost-client/src/client.coffee:1:1, <js>:3:61
  at IncomingMessage.<anonymous> (/home/i055636/git/alfred/node_modules/mattermost-client/src/client.coffee:316:25, <js>:427:22)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:926:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

> [Tue May 31 2016 22:32:02 GMT+0530 (IST)] INFO Connected to Lattermost.

From what I understand looking at client.coffee code, I see that the call to get the list of channels fails. I also don't see any info on the profiles loaded. Although hubot starts fine, I don't get any response when messaging the bot, and for every message I see the below error - which is obviously because the channel info was not fetched earlier.

> [Tue May 31 2016 22:38:38 GMT+0530 (IST)] INFO ACK ping
[Tue May 31 2016 22:38:52 GMT+0530 (IST)] ERROR TypeError: Cannot read property 'cjafy4wg47ykzgkpdnrwd6ojsa' of undefined
  at Client.getChannelByID (/home/i055636/git/alfred/node_modules/mattermost-client/src/client.coffee:247:9, <js>:333:27)
  at Matteruser.message (/home/i055636/git/alfred/node_modules/hubot-matteruser/src/matteruser.coffee:122:21, <js>:195:33)
  at Client.<anonymous> (/home/i055636/git/alfred/node_modules/hubot-matteruser/src/matteruser.coffee:1:1, <js>:3:61)
  at emitOne (events.js:96:13)
  at Client.emit (events.js:188:7)
  at Client.onMessage (/home/i055636/git/alfred/node_modules/mattermost-client/src/client.coffee:206:17, <js>:274:23)
  at WebSocket.<anonymous> (/home/i055636/git/alfred/node_modules/mattermost-client/src/client.coffee:154:13, <js>:213:22)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.ontext (/home/i055636/git/alfred/node_modules/ws/lib/WebSocket.js:841:10)
  at /home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:371:5)
  at /home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.opcodes.1.finish (/home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/home/i055636/git/alfred/node_modules/ws/lib/Receiver.js:103:24)
  at TLSSocket.realHandler (/home/i055636/git/alfred/node_modules/ws/lib/WebSocket.js:825:20)
  at emitOne (events.js:96:13)
  at TLSSocket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:172:18)
  at TLSSocket.Readable.push (_stream_readable.js:130:10)
  at TLSWrap.onread (net.js:542:20)

Could you please let me know how I can fix this? Am I missing something from my end or is this a possible bug?

Regards,
Anand

**Comment by loafoe** [comment]
@msanand which version of Mattermost server and which version of `hubot-matteruser` are you using?

**Comment by msanand** [comment]
@loafoe 
Mattermost Team Edition: Version: 3.0.0 (3.0.2)
"hubot-matteruser": "^3.1.0",

**Comment by msanand** [comment]
Identified the root cause. The problem occurs when the team/group name does not match the same case as specified in the URL. I had used the name which is displayed instead of the one on the URL.
This should either be clearly documented or the adapted should accept either values.
