### ISSUE TITLE
_onInitialLoad sometimes fails with "Object.keys called on non-object

### ISSUE THREAD

**Issue by campbellr** [loafoe/mattermost-client#14]
I use mattermost-client as part of hubot-matteruser, and every once in a while i will notice that hubot is no longer logged in.

 When i look at the logs i see something like this:

```
2016-06-06T23:31:47.76-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:47 GMT+0000 (UTC)] ERROR Last pong is too old: 113.898
2016-06-06T23:31:47.76-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:47 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
2016-06-06T23:31:48.76-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:48 GMT+0000 (UTC)] INFO Attempting reconnect
2016-06-06T23:31:48.76-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:48 GMT+0000 (UTC)] INFO Logging in...
2016-06-06T23:31:48.76-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:48 GMT+0000 (UTC)] DEBUG POST /users/login
2016-06-06T23:31:48.97-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:48 GMT+0000 (UTC)] INFO Websocket URL: wss://mattermost.example.com:443/api/v3/users/websocket
2016-06-06T23:31:48.97-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:48 GMT+0000 (UTC)] INFO Logged in as user "hubot" but not connected yet.
2016-06-06T23:31:48.97-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:48 GMT+0000 (UTC)] DEBUG GET /users/initial_load
2016-06-06T23:31:49.11-0600 [APP/0]      OUT [Tue Jun 07 2016 05:31:49 GMT+0000 (UTC)] ERROR TypeError: Object.keys called on non-object
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at Function.keys (native)        
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at Client._onInitialLoad (/home/vcap/app/node_modules/mattermost-client/src/client.coffee:68:13, <js>:100:45)
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at /home/vcap/app/node_modules/mattermost-client/src/client.coffee:1:1, <js>:3:61
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/mattermost-client/src/client.coffee:313:25, <js>:433:22)
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at IncomingMessage.emit (events.js:117:20)
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at _stream_readable.js:944:16    
2016-06-06T23:31:49.11-0600 [APP/0]      OUT   at process._tickCallback (node.js:458:13)


```

I suspect this is due to some error condition in `_apiCall`. On error the the method calls `callback`, but with a special error object. Unfortunately it doesn't look like any users of `_apiCall` bother to check whether or not an error occurred...

**Comment by loafoe** [comment]
@campbellr Added error checks in callback. If possible please test against `master`. This fix will be in the next release.
